# Generated by Django 5.2.12 on 2026-03-21 23:05

from pathlib import Path

from django.conf import settings
from django.db import migrations

from vault.storage import sanitize_segment


def export_note_bodies_to_files(apps, schema_editor):
    """Write legacy DB column body to the vault markdown path before dropping the column."""
    Note = apps.get_model('vault', 'Note')
    Folder = apps.get_model('vault', 'Folder')
    User = apps.get_model('auth', 'User')

    def folder_path_segments(folder):
        parts = []
        current = folder
        while current is not None:
            parts.insert(0, sanitize_segment(current.name))
            pid = current.parent_id
            if pid:
                current = Folder.objects.get(pk=pid)
            else:
                current = None
        return parts

    # If body column was already removed, there is nothing to export.
    connection = schema_editor.connection
    columns = [col.name for col in connection.introspection.get_table_description(connection.cursor(), 'vault_note')]
    if 'body' not in columns:
        return

    base_root = Path(settings.VAULT_ROOT).resolve()

    for note in Note.objects.iterator():
        user = User.objects.get(pk=note.user_id)
        base = base_root / sanitize_segment(user.username)
        if note.folder_id:
            folder = Folder.objects.get(pk=note.folder_id)
            rel = Path(*folder_path_segments(folder))
            path = (base / rel / f'{sanitize_segment(note.name)}.md').resolve()
        else:
            path = (base / f'{sanitize_segment(note.name)}.md').resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        text = note.body or ''
        path.write_text(text, encoding='utf-8')


def drop_body_column(apps, schema_editor):
    schema_editor.execute('ALTER TABLE vault_note DROP COLUMN IF EXISTS body')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_pin'),
    ]

    operations = [
        migrations.RunPython(export_note_bodies_to_files, noop_reverse),
        migrations.RunPython(drop_body_column, noop_reverse),
    ]
