# Generated by Django 5.2.13 on 2026-04-21 07:17

from django.db import migrations, connection


def remove_body_if_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'vault_note' AND column_name = 'body'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER TABLE vault_note DROP COLUMN body')


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_usersettings'),
    ]

    operations = [
        migrations.RunPython(remove_body_if_exists, migrations.RunPython.noop),
    ]
