# Generated by Django 5.2.12 on 2026-04-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
    ]
