# Generated by Django 5.2.13 on 2026-04-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
    ]
